const menu = [
    {
     id: 1,
    title: 'buttermilk pancakes',
    category:'Breakfast',
    price:85,
    img:'./images/2.jpeg',
    desc:`The tangy flavor of buttermilk is not the only reason it’s important in creating the perfect buttermilk pancake. Buttermilk actually helps to activate the baking soda or raising agent in the pancake batter. This means before the pancake even hits the heat, it’s being made light and fluffy and bubbly from within the batter.`,
},
{
id: 2,
    title: 'fruit & south',
    category:'Breakfast',
    price:45,
    img:'./images/4.jpeg',
    desc:`The tangy flavor of buttermilk is not the only reason it’s important in creating the perfect buttermilk pancake. Buttermilk actually helps to activate the baking soda or raising agent in the pancake batter. This means before the pancake even hits the heat, it’s being made light and fluffy and bubbly from within the batter.`,
},

{ id: 3,
    title: 'south indian',
    category:'Breakfast',
    price:85,
    img:'./images/5.jpeg',
    desc:`The tangy flavor of buttermilk is not the only reason it’s important in creating the perfect buttermilk pancake. Buttermilk actually helps to activate the baking soda or raising agent in the pancake batter. This means before the pancake even hits the heat, it’s being made light and fluffy and bubbly from within the batter.`,
},
{
id: 4,
    title: 'tea and biscuits',
    category:'Breakfast',
    price:65,
    img:'./images/6.jpeg',
    desc:`The tangy flavor of buttermilk is not the only reason it’s important in creating the perfect buttermilk pancake. Buttermilk actually helps to activate the baking soda or raising agent in the pancake batter. This means before the pancake even hits the heat, it’s being made light and fluffy and bubbly from within the batter.`,
},
{
    id: 5,
    title: 'bread & coffe',
    category:'Breakfast',
    price:75,
    img:'./images/7.jpeg',
    desc:`The tangy flavor of buttermilk is not the only reason it’s important in creating the perfect buttermilk pancake. Buttermilk actually helps to activate the baking soda or raising agent in the pancake batter. This means before the pancake even hits the heat, it’s being made light and fluffy and bubbly from within the batter.`,
},
{
    id: 6,
    title: 'dhosa',
    category:'Lunch',
    price:175,
    img:'./images/9.jpeg',
    desc:`The tangy flavor of buttermilk is not the only reason it’s important in creating the perfect buttermilk pancake. Buttermilk actually helps to activate the baking soda or raising agent in the pancake batter. This means before the pancake even hits the heat, it’s being made light and fluffy and bubbly from within the batter.`,
},
{
id: 7,
title: 'paratha',
category:'Breakfast',
price:100,
img:'./images/8.jpeg',
desc:`The tangy flavor of buttermilk is not the only reason it’s important in creating the perfect buttermilk pancake. Buttermilk actually helps to activate the baking soda or raising agent in the pancake batter. This means before the pancake even hits the heat, it’s being made light and fluffy and bubbly from within the batter.`,
},

{
    id: 8,
    title: 'full-dish punjabi',
    category:'Lunch',
    price:280,
    img:'./images/10.jpeg',
    desc:`The tangy flavor of buttermilk is not the only reason it’s important in creating the perfect buttermilk pancake. Buttermilk actually helps to activate the baking soda or raising agent in the pancake batter. This means before the pancake even hits the heat, it’s being made light and fluffy and bubbly from within the batter.`,
},
{
    id: 9,
    title: 'kathiyawadi dish',
    category:'Lunch',
    price:180,
    img:'./images/11.jpeg',
    desc:`The tangy flavor of buttermilk is not the only reason it’s important in creating the perfect buttermilk pancake. Buttermilk actually helps to activate the baking soda or raising agent in the pancake batter. This means before the pancake even hits the heat, it’s being made light and fluffy and bubbly from within the batter.`,
},
{
id: 10,
title: 'chhole-puri',
category:'Lunch',
price:120,
img:'./images/12.jpeg',
desc:`The tangy flavor of buttermilk is not the only reason it’s important in creating the perfect buttermilk pancake. Buttermilk actually helps to activate the baking soda or raising agent in the pancake batter. This means before the pancake even hits the heat, it’s being made light and fluffy and bubbly from within the batter.`,
},
{
    id: 11,
    title: 'gujrati thali',
    category:'Lunch',
    price:250,
    img:'./images/13.jpeg',
    desc:`The tangy flavor of buttermilk is not the only reason it’s important in creating the perfect buttermilk pancake. Buttermilk actually helps to activate the baking soda or raising agent in the pancake batter. This means before the pancake even hits the heat, it’s being made light and fluffy and bubbly from within the batter.`,
},
{
    id: 12,
    title: 'palakh panner with rice',
    category:'Lunch',
    price:180,
    img:'./images/14.jpeg',
    desc:`The tangy flavor of buttermilk is not the only reason it’s important in creating the perfect buttermilk pancake. Buttermilk actually helps to activate the baking soda or raising agent in the pancake batter. This means before the pancake even hits the heat, it’s being made light and fluffy and bubbly from within the batter.`,
},
{
    id: 13,
    title: 'strawbarry & coconut shake',
    category:'Shake',
    price:210,
    img:'./images/15.jpeg',
    desc:`The tangy flavor of buttermilk is not the only reason it’s important in creating the perfect buttermilk pancake. Buttermilk actually helps to activate the baking soda or raising agent in the pancake batter. This means before the pancake even hits the heat, it’s being made light and fluffy and bubbly from within the batter.`,
},
{
    id: 14,
    title: 'breakfast-shake',
    category:'Shake',
    price:80,
    img:'./images/16.jpeg',
    desc:`The tangy flavor of buttermilk is not the only reason it’s important in creating the perfect buttermilk pancake. Buttermilk actually helps to activate the baking soda or raising agent in the pancake batter. This means before the pancake even hits the heat, it’s being made light and fluffy and bubbly from within the batter.`,
},
{
    id: 15,
    title: 'chocolate shake',
    category:'Shake',
    price:250,
    img:'./images/17.jpeg',
    desc:`The tangy flavor of buttermilk is not the only reason it’s important in creating the perfect buttermilk pancake. Buttermilk actually helps to activate the baking soda or raising agent in the pancake batter. This means before the pancake even hits the heat, it’s being made light and fluffy and bubbly from within the batter.`,
},
{
    id: 16,
    title: 'pista with strawberry shake',
    category:'Shake',
    price:145,
    img:'./images/18.jpeg',
    desc:`The tangy flavor of buttermilk is not the only reason it’s important in creating the perfect buttermilk pancake. Buttermilk actually helps to activate the baking soda or raising agent in the pancake batter. This means before the pancake even hits the heat, it’s being made light and fluffy and bubbly from within the batter.`,
},
{
    id: 17,
    title: 'crazy shake',
    category:'Shake',
    price:135,
    img:'./images/19.jpeg',
    desc:`The tangy flavor of buttermilk is not the only reason it’s important in creating the perfect buttermilk pancake. Buttermilk actually helps to activate the baking soda or raising agent in the pancake batter. This means before the pancake even hits the heat, it’s being made light and fluffy and bubbly from within the batter.`,
},
{
    id: 18,
    title: 'shamrock shake',
    category:'Shake',
    price:195,
    img:'./images/20.jpeg',
    desc:`The tangy flavor of buttermilk is not the only reason it’s important in creating the perfect buttermilk pancake. Buttermilk actually helps to activate the baking soda or raising agent in the pancake batter. This means before the pancake even hits the heat, it’s being made light and fluffy and bubbly from within the batter.`,
}
];


export default menu;
